### PR TITLE
Swik 802 investigate implement import of diagrams from pptx to slide wiki

### PR DESCRIPTION
**Pull request by sednanref**
The links are now supported with the last commits, the styles now are correct and you can get redirected by clicking on them.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
When importing 
[Got the Tech final with notes, Abi James ATEC.pptx](https://github.com/slidewiki/import-service/files/631289/Got.the.Tech.final.with.notes.Abi.James.ATEC.pptx)

I get error (on http://log.experimental.slidewiki.org/): 

 slidewiki/importservice experimental Debug: internal, implementation, error

slidewiki/importservice experimental TypeError: Uncaught error: Cannot read property 'rId3' of undefined

slidewiki/importservice experimental at Convertor.genSpanElement (/nodeApp/PPTX2HTML/js/convertor.js:1525:43)

slidewiki/importservice experimental at Convertor.genTextBody (/nodeApp/PPTX2HTML/js/convertor.js:1229:25)

slidewiki/importservice experimental at Convertor.genShape (/nodeApp/PPTX2HTML/js/convertor.js:1021:23)

slidewiki/importservice experimental at Convertor.processSpNode (/nodeApp/PPTX2HTML/js/convertor.js:688:14)

slidewiki/importservice experimental at Convertor.processNodesInSlide (/nodeApp/PPTX2HTML/js/convertor.js:571:18)

slidewiki/importservice experimental at Convertor.processSingleSlideNotes (/nodeApp/PPTX2HTML/js/convertor.js:484:27)

slidewiki/importservice experimental at Convertor.convertFirstSlide (/nodeApp/PPTX2HTML/js/convertor.js:92:40)

slidewiki/importservice experimental at importPPTX (/nodeApp/controllers/handler.js:143:35)

slidewiki/importservice experimental at Object.internals.handler (/nodeApp/node_modules/hapi/lib/handler.js:96:36)

slidewiki/importservice experimental at request._protect.run (/nodeApp/node_modules/hapi/lib/handler.js:30:23)

 slidewiki/importservice experimental Debug: internal, implementation, error

slidewiki/importservice experimental TypeError: Uncaught error: Cannot read property 'rId3' of undefined

slidewiki/importservice experimental at Convertor.genSpanElement (/nodeApp/PPTX2HTML/js/convertor.js:1525:43)

slidewiki/importservice experimental at Convertor.genTextBody (/nodeApp/PPTX2HTML/js/convertor.js:1229:25)

slidewiki/importservice experimental at Convertor.genShape (/nodeApp/PPTX2HTML/js/convertor.js:1021:23)

slidewiki/importservice experimental at Convertor.processSpNode (/nodeApp/PPTX2HTML/js/convertor.js:688:14)

slidewiki/importservice experimental at Convertor.processNodesInSlide (/nodeApp/PPTX2HTML/js/convertor.js:571:18)

slidewiki/importservice experimental at Convertor.processSingleSlideNotes (/nodeApp/PPTX2HTML/js/convertor.js:484:27)

slidewiki/importservice experimental at Convertor.convertFirstSlide (/nodeApp/PPTX2HTML/js/convertor.js:92:40)

slidewiki/importservice experimental at importPPTX (/nodeApp/controllers/handler.js:143:35)

slidewiki/importservice experimental at Object.internals.handler (/nodeApp/node_modules/hapi/lib/handler.js:96:36)

slidewiki/importservice experimental at request._protect.run (/nodeApp/node_modules/hapi/lib/handler.js:30:23)

slidewiki/importservice experimental 161205/140750.398, [response,api] http://64ecfc3731f1:80: [1;33mpost[0m /importPPTX {} [31m500[0m (276ms) 

So I'll revert the commit for now

**Comment by sednanref** [comment]
Hi @kadevgraaf , I'm trying to reproduce this error but every time I try to import that file I get this error:

importservice_1 | Debug: internal, implementation, error 
importservice_1 |     Error: Uncaught error: ENOENT: no such file or directory, mkdir '/data/files/39'
importservice_1 |     at Error (native)
importservice_1 |     at Object.fs.mkdirSync (fs.js:922:18)
importservice_1 |     at Convertor.saveImageToFile (/dockerApp/PPTX2HTML/js/convertor.js:1109:8)
importservice_1 |     at Convertor.processPicNode (/dockerApp/PPTX2HTML/js/convertor.js:1070:26)
importservice_1 |     at Convertor.processNodesInSlide (/dockerApp/PPTX2HTML/js/convertor.js:571:18)
importservice_1 |     at Convertor.processSingleSlide (/dockerApp/PPTX2HTML/js/convertor.js:399:20)
importservice_1 |     at Convertor.convertFirstSlide (/dockerApp/PPTX2HTML/js/convertor.js:91:42)
importservice_1 |     at importPPTX (/dockerApp/controllers/handler.js:143:35)
importservice_1 |     at Object.internals.handler (/dockerApp/node_modules/hapi/lib/handler.js:96:36)
importservice_1 |     at request._protect.run (/dockerApp/node_modules/hapi/lib/handler.js:30:23)
importservice_1 | 161205/145248.329, [response] http://ba59c689d590:80: post /importPPTX {} 500 (304ms)

I created the path in my local machine and in the docker machine... so I don't understand why it keeps saying that the folder doesn't exist, do you know why is that? Is there something I need to configure to allow images storage?

**Comment by kadevgraaf** [comment]
Hi @sednanref!
What file were you using for testing before?

On #storage we talked about the error above, and @dpaun suggested that it might be related with speaker notes (which also have HTML content and I think can also contain hyperlinks) - perhaps it might be solved by also applying this fix for the part of convertor.js that handles nodes (or remove/adapt the fix for notes if it was already applied))

**Comment by dpaun** [comment]
Hi, @sednanref!
Please, see lines 1106 and 1110 of convertor.js [here](https://github.com/slidewiki/import-service/blob/master/application/PPTX2HTML/js/convertor.js#L1106) for saving images locally on Linux.

**Comment by sednanref** [comment]
hi @kadevgraaf I used this file which is a simple one with 2 links and a chart,
[test2.pptx](https://github.com/slidewiki/import-service/files/631454/test2.pptx)


Thanks @dpaun and @kadevgraaf  for the infor! I'll try it right now

**Pull request merged**
