### PR TITLE
Dynamic document.domain based on fix PR 611 in platform

### PR DESCRIPTION
**Pull request by kadevgraaf**

### CODE REVIEW

**Comment by TBoonX** [comment]
Please fix this also a few lines above.

**Comment by kadevgraaf** [comment]
Thanks for identifying this! 
I now also fixed domain a few lines above.

**Comment by TBoonX** [comment]
I tested this on the domain slidewiki.aksw.org and it worked. I did not had the time to test it on localhost.

**Comment by kadevgraaf** [comment]
Cool. Thanks for testing!

**Pull request merged**
